### ISSUE TITLE
Does not build

### ISSUE THREAD

**Issue by andrewb-ms** [danprince/docker-pm2-example#1]
$ sudo docker build .
Sending build context to Docker daemon 107.5 kB
Step 1/5 : FROM keymetrics/pm2-docker-alpine:latest
repository keymetrics/pm2-docker-alpine not found: does not exist or no pull access

**Comment by danprince** [comment]
Looks like they renamed the tags for the Alpine builds: https://github.com/keymetrics/docker-pm2

**Comment by danprince** [comment]
Just pushed a change to switch it out for `keymetrics/pm2:latest-alpine`. Feel free to re-open this issue if you're still seeing problems.

**Comment by andrewb-ms** [comment]
Thanks!
